### ISSUE TITLE
Xcode 14/MacOs 13 installation failure

### ISSUE THREAD

**Issue by Quadriphobs1** [michaeleisel/zld#115]
Installling zld on MacOs 13 with Xcode 14 beta kept failing with the same error message

<img width="900" alt="Screenshot 2022-08-08 at 10 47 58 pm" src="https://user-images.githubusercontent.com/20229808/183422030-dd02478c-b46a-4381-8c41-e217d06c70b4.png">

**Comment by michaeleisel** [comment]
Can you show the failing link command? Also, is using pre-built zld an option for you?

**Comment by DianaSensei** [comment]
![image](https://user-images.githubusercontent.com/43933486/190840854-0d109043-0d2b-43ff-8a9e-246663ea8cbf.png)
I have the same issue when install in Monterey 12.6/Xcode 14.0 (14A309)

**Comment by Tam** [comment]
Here's the error from my log file:

```
/Applications/Xcode.app/ContentsUndefined symbols for architecture x86_64:
  "tapi::v1::LinkerInterfaceFile::getPlatform() const", referenced from:
      textstub::dylib::File<x86_64>::init(tapi::v1::LinkerInterfaceFile*, Options const*, bool, bool, bool, bool, char const*, ld::VersionSet const&, char const*, bool, bool, bool, bool) in textstub_dylib_file.o
      textstub::dylib::File<x86>::init(tapi::v1::LinkerInterfaceFile*, Options const*, bool, bool, bool, bool, char const*, ld::VersionSet const&, char const*, bool, bool, bool, bool) in textstub_dylib_file.o
      textstub::dylib::File<arm>::init(tapi::v1::LinkerInterfaceFile*, Options const*, bool, bool, bool, bool, char const*, ld::VersionSet const&, char const*, bool, bool, bool, bool) in textstub_dylib_file.o
      textstub::dylib::File<arm64>::init(tapi::v1::LinkerInterfaceFile*, Options const*, bool, bool, bool, bool, char const*, ld::VersionSet const&, char const*, bool, bool, bool, bool) in textstub_dylib_file.o
ld: symbol(s) not found for architecture x86_64
/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/lib/system/libmacho.tbd
```

**Comment by michaeleisel** [comment]
now fixed in 1.3.8

**Comment by Quadriphobs1** [comment]
Tried with 1.3.8 and still can't install via the binary build with the following error

<img width="577" alt="image" src="https://user-images.githubusercontent.com/20229808/192915837-45160580-62ec-4b10-9b0e-4a2edc28ea8e.png">

Tried installing via homebrew and the error reported is about Xcode 14 cli tool despite having Xcode 14 and the new CLI tool

<img width="726" alt="image" src="https://user-images.githubusercontent.com/20229808/192916062-d2c560de-a0e6-41c0-b5a6-8f8adb43e0dc.png">
